### ISSUE TITLE
Load balancer wasn't ready

### ISSUE THREAD

**Issue by nyazadzhiev** [MicrosoftDocs/mslearn-aspnet-core#179]
I get this error while running the quickstart script
kubectl get svc -n ingress-nginx -o json | jq -r -e '.items[0].status.loadBalancer.ingress[0].ip // empty'

The connection to the server localhost:8080 was refused - did you specify the right host or port?
Load balancer wasn't ready. If this takes more than a minute or two, something is probably wrong. Trying again in 5 seconds...

**Comment by ngothiensinh** [comment]
Same error here but seem the JQ is not support natively on windows.
To fix it:
- download jq.exe for windows
- edit the command like this:
`eshopLbIpCommand="kubectl get svc -n ingress-nginx -o json | '/c/Downloads/jq-win64.exe' -r -e '.items[0].status.loadBalancer.ingress[0].ip // empty'"`

**Comment by CamSoper** [comment]
These scripts aren't intended to run outside of the dev container (or Codespaces) environment.
