### ISSUE TITLE
dotnet-aspnet-codegenerator not installing, compatibility mismatch

### ISSUE THREAD

**Issue by kingpric** [MicrosoftDocs/mslearn-aspnet-core#21]
$> dotnet tool install -g dotnet-aspnet-codegenerator

error NU1202: Package dotnet-aspnet-codegenerator 3.0.0 is not compatible with netcoreapp2.2 (.NETCoreApp,Version=v2.2) / any. Package dotnet-aspnet-codegenerator 3.0.0 supports: netcoreapp3.0 (.NETCoreApp,Version=v3.0) / any
Tool 'dotnet-aspnet-codegenerator' failed to update due to the following:
The tool package could not be restored.
Tool 'dotnet-aspnet-codegenerator' failed to install. This failure mayhave been caused by:

* You are attempting to install a preview release and did not use the --version option to specify the version.
* A package by this name was found, but it was not a .NET Core tool.
* The required NuGet feed cannot be accessed, perhaps because of an Internet connection problem.
* You mistyped the name of the tool.

**Comment by CamSoper** [comment]
@kingpric Thanks for the heads-up. Looks like the `dotnet tool install` command always pulls latest stable, which is currently 3.0. This is unfortunate because this tutorial is pinned to 2.2.

Thanks for the detailed issue, though! The title the issue describing this same bug we got from another user through the MS Learn system was "this tutorial sucks." Point taken, I'm working on it. 😆

**Comment by CamSoper** [comment]
Fixed with https://github.com/MicrosoftDocs/mslearn-aspnet-core/pull/23

**Comment by Thobekanii** [comment]
azorPagesMovie/RazorPagesMovie.csproj : error NU1202: Package dotnet-aspnet-codegenerator 2.2.4 is not compatible with netcoreapp2.2 (.NETCoreApp,Version=v2.2). Package dotnet-aspnet-codegenerator 2.2.4 supports: netcoreapp2.1 (.NETCoreApp,Version=v2.1) / any
/Users/thobe/RazorPagesMovie/RazorPagesMovie.csproj : error NU1212: Invalid project-package combination for dotnet-aspnet-codegenerator 2.2.4. DotnetToolReference project style can only contain references of the DotnetTool type.

any version above or below 2.2.4 is not compatible with  NETCoreApp,Version=v2.2 in my machine. @CamSoper
