### ISSUE TITLE
Error at Contoso Pets ProductsAdmin page

### ISSUE THREAD

**Issue by J4DR3** [MicrosoftDocs/mslearn-aspnet-core#35]
Hello, after setting up the development environment, and running the dotnet run and az webapp up commands I'm able to connect to my webpage URL. In Products Admin page this error appears:

An error occurred while processing your request.
Request ID: 8000160a-0000-e800-b63f-84710c7967bb 
Development Mode
Swapping to the Development environment displays detailed information about the error that occurred. 
The Development environment shouldn't be enabled for deployed applications. It can result in displaying sensitive information from exceptions to end users. For local debugging, enable the Development environment by setting the ASPNETCORE_ENVIRONMENT environment variable to Development and restarting the app. 

The page does not display the list of products and I can't edit or delete an existing product, as shown in 
https://docs.microsoft.com/en-us/learn/modules/create-razor-pages-aspnet-core/4-run-razor-pages-project

It makes it impossible to follow the tutorial, I've tried restarting the CloudShell terminal, re-running all of the commands provided with no luck.

**Comment by scottaddie** [comment]
@J4DR3 Thank you for reporting this problem. It's fixed now.
