### ISSUE TITLE
Error during run. Key vault has mandatory parameter now.

### ISSUE THREAD

**Issue by SeSeKenny** [MicrosoftDocs/mslearn-aspnet-core#38]
infrastructure/scripts/provisioning/keyvault.sh

--enable-soft-delete is required now or the creation will fail. There was a doc earlier on that was also broken because of this, but i could modify it easy (just copy and paste command stuff). Now I am going to try and set a default for this so the script runs and I can finish training for my exam.

https://docs.microsoft.com/en-ca/learn/modules/secure-aspnet-core-identity/2-setup-environment?pivots=sql

Set up dev environment.

**Comment by SeSeKenny** [comment]
need to have a key vault policy setup too. commands to add secrets fail

**Comment by CamSoper** [comment]
Thank you @SeSeKenny! Should be fixed now, if you'd like to try it again.
