### ISSUE TITLE
[Question] How to run it locally 

### ISSUE THREAD

**Issue by PingPongSet** [MicrosoftDocs/mslearn-aspnet-core#86]
I followed the steps on the link below running it from Azure Cloud Shell,
https://docs.microsoft.com/en-us/learn/modules/microservices-aspnet-core/2-deploy-application

My question is that how to run it locally from my machine instead, if possible?

**Comment by justinbourb** [comment]
I have the same question.  Please update the readme with instructions on how to get this project to run locally.
This repo is used in one of the dotNET [tutorial videos](https://www.youtube.com/watch?v=Q_59nDCezuU&list=PLdo4fOcmZ0oVxKLQCHpiUWun7vlJJvUiN&index=23)  but there are no instructions how to run this code.
